language: r
cache: packages
r: 
  - oldrel
  - release
  - devel
notifications:
  email:
    recepients:
     - andrea.rau@inra.fr
    on_success: change
    on_failure: change
git:
  depth: false
branches:
  only:
  - master
  - stable