language: r
cache: packages
r: 
  - release
notifications:
  email:
    recepients:
     - andrea.rau@inra.fr
    on_success: change
    on_failure: change
git:
  depth: false
branches:
  only:
  - master
  - stable
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true